Solve #39
Snakemake-Profiles/lsf pull request #40
Opened 2021-03-07 19:31 UTC by bricoletc

I found a case, described in #39, which failed on lsf cluster.
I propose here a solution which made it run successfully.

## Added

- Support for complex quote-expansion via `shlex` [#39]
- Function docstrings in `lsf_config.py` for documentation

Some details of the changes:

#39 issue:
 * The split argument string needs to be rejoined using `shlex`
 * Two unit tests for `lsf_config.py` to ensure quotes are shell-escaped
 * One modified unit test for `lsf_submit.py` to ensure quotes are
    shell-escaped
 * Rewrote `__init__` of `Config` object, to directly concatenate
    parameter lists. Makes downstream argument string production simpler to
    read.
 * Added function docstrings in `lsf_config.py` to make understanding easier

Docs/gitignore:
 * Add vim and venv to gitignore
 * Add example of complex quote escaping in `lsf.yaml` in the readme

The tests  pass- I've not tested this exact version of the code on the cluster, so maybe should do that too.
Cheers!

2021-03-08 09:32 UTC, leoisl approved these changes
All looks fine to me!

2021-03-09 04:35 UTC, mbhall88 requested changes
Great catch @bricoletc! I didn't know shlex had a join function.

Just some tiny doc updates

2021-03-09 04:35 UTC, mbhall88 commented on README.md
> +#### Example `lsf.yaml` configuration
```suggestion
#### Examples
```

2021-03-09 04:35 UTC, mbhall88 commented on README.md
> +#### Quote-escaping in `lsf.yaml`
```suggestion
#### Quote-escaping
```

2021-03-09 04:35 UTC, mbhall88 commented on README.md
> +Some lsf commands require multiple levels of quote-escaping.
```suggestion
Some LSF commands require multiple levels of quote-escaping.
```

2021-03-09 04:35 UTC, mbhall88 commented on {{cookiecutter.profile_name}}/lsf_config.py
> +        Converts a string into a dictionary where key/value pairs are consecutive
```suggestion
        """Converts a string into a dictionary where key/value pairs are consecutive
```

2021-03-09 04:37 UTC, mbhall88 commented
Ah actually, I've just realised why the CI is failing. `shlex.join` was only added in python 3.8 (and also black formatting is failing). I would suggest using python 3.5 in your local venv for this project.

2021-03-09 22:06 UTC, bricoletc commented
Ok! I found a workaround using python3.5-compatible `shlex` invocations.

For failing the black formatting, I see what you're doing; snakemake supports python>=3.5, but black is for python3.6+ only, so you dont install black using `dev-requirements.txt` else that would fail python3.5 CI. I added a note in `CONTRIBUTING.md` saying you need to install latest black- that means CI will pass.

2021-03-12 07:03 UTC, mbhall88 approved these changes
Thanks a lot Brice

2021-03-12 07:03 UTC, merged